### PR TITLE
More detailed time taken reporting

### PR DESCRIPTION
**Pull request by vitoc**
# Change type 

- [ ] Bug fix
- [ ] New feature
- [x] Enhancement
- [ ] Breaking change (breaks backward compatibility)

**Checklist:**

- [x] All tests passed
- [x] The code follows the code style and conventions of this project
- [ ] The change requires a change to the documentation
- [ ] I have updated the documentation accordingly

# Description and Motivation 
This change will show more "time taken" information vs just one. The original time taken does not encompass the whole process anyway and being more verbose here may help clarify the time disparity observed in #170

### CODE REVIEW

**Comment by ppathan** [comment]
The requirement that we have right now is to show total time taken for the solution deployment, we should probably work on that.

**Comment by dluc** [comment]
@vitoc could you include a quick screenshot showing the difference? something we've been thinking about is also measuring the time spent on each resource. Thanks

**Comment by vitoc** [comment]
The timers show time passed by what I thought of as "activities". I.e., app registration, resource group creation (which I now realize is pretty fast, like 0-5 seconds, hence maybe negligible) and then the actual resource provisioning. 

activitytimetakenmasked

I like the idea of showing time taken for each resource provisioned. I think having more information, timing included, is great. I have a verbose inclination when it involves the CLI :)

**Comment by dluc** [comment]
I like the idea of showing timing on each step, however we need to balance the amount of verbosity with the excess of information that could make for a worse experience. Looking at the screenshot, it gives me the impression of "too much noise", so I rather make the change only if we find a nice format. For instance there are some ways (perhaps with other libs) to align the time passed either in front (on the left) or at the right of the screen, so that the final result is still pretty an easy to read.
Summarizing, before making a similar change, I'd like to find a nice format covering all the steps, and making the change all at once.

**Comment by vitoc** [comment]
Yeah, agree.

**Comment by vitoc** [comment]
Looking towards the next format of activity/steps and time output/indicator.

**Pull request closed without merging**
