### PR TITLE
Add initial DEVELOPMENT.md

### PR DESCRIPTION
**Pull request by vitoc**
# Description and Motivation 

Just suggesting a brief DEVELOPMENT.md to ease the journey of those looking to start dabbling with pcs-cli code.

### CODE REVIEW

**Comment by timlaverty** [comment]
This is actually where we started - we used to have a development.md and a readme.md.  We found the info. across the two split poorly and in our hackathons many folks asked us to combine them (which is why we have the single readme).  Happy to discuss further but for now I want to leave this as-is unless we continue to receive feedback for a desire to split.

**Comment by vitoc** [comment]
Ah, ok. Thanks for the note. Will it be OK if I add a high level dev note on CONTRIBUTING.md instead? (See latest commit). Thing is, the link does say "Contributing and Development setup".

**Comment by ppathan** [comment]
I think we should call it "Contributing" in the README

**Comment by vitoc** [comment]
OK, summed up the PR as that :)

**Pull request merged**
